# Generated by Django 3.2.4 on 2021-07-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewletterUsers',
            new_name='NewletterUser',
        ),
    ]
