# Generated by Django 3.2.4 on 2021-07-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
