# Generated by Django 3.2.4 on 2021-07-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_subscribemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribeModel',
            new_name='Subscribers',
        ),
    ]
