# Generated by Django 3.2.4 on 2021-07-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
